### PR TITLE
Update cohttp and uri imports for example server

### PR DESCRIPTION
**Pull request by anuragsoni**
Signed-off-by: Anurag Soni <anuragsoni.13@gmail.com>

### CODE REVIEW

**Comment by anuragsoni** [comment]
The example server on the current master has compilation errors.

**Comment by ghost** [comment]
I'm looking at this. The fix will be a bit different. The idea is that internally we don't allow libraries to export more than one toplevel module. We have a workaround for importing external libraries but it's applied on a case-by-case basis. That's why the names are wrong in the examples.

**Comment by ghost** [comment]
I tried but it's not straightforward as it creates a lot of name clashes since we have many files called `uri.ml` in our tree. I'll give it another try later.

**Comment by anuragsoni** [comment]
Oh okay. I assumed that the example server just needed to be a basic Cohttp server, mostly used for the client demo.

**Pull request closed without merging**
