### PR TITLE
Update to new JavaScript-Promise Integration API

### PR DESCRIPTION
**Pull request by vouillon**

### CODE REVIEW

**Comment by rickyvetter** [comment]
When I tried this I get an error in node `v23.0.0-v8-canary2024100880fe21ab46`: 

```
RuntimeError: attempting to suspend without a WebAssembly.promising export
```

Reading https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md, I think there is more work required. We need to implement the `promising` part of the pair, which is awkward because I don't think there is current machinery for inserting JavaScript code into the runtime which has access to some corresponding wasm export values.

Did you run into this error? Which version of node were you running against if not?

**Comment by vouillon** [comment]
I think you need https://github.com/ocaml-wasm/wasm_of_ocaml/pull/48 as well.
I have tested with an older version of node, `v23.0.0-v8-canary2024070398c15bef2c`, which supports both APIs.

**Comment by rickyvetter** [comment]
Ahh yes. With https://github.com/ocaml-wasm/wasm_of_ocaml/pull/48 this does look good!

**Comment by rickyvetter** [comment]
I've noticed that I do get an error when running with whole program compilation and aggressive `wasm-metadce` passes on tests that don't use effects. I can resolve by editing https://github.com/ocaml-wasm/wasm_of_ocaml/blob/main/runtime/wasm/deps.json#L4 to include "effects", which I think is the correct fix? It might make more sense to try and generate deps.json somehow?

**Comment by vouillon** [comment]
Actually, we don't need `caml_start_fiber` for tests that don't use effects. The issue is that `make_promising` is failing when passed an undefined value. I have pushed a fix to https://github.com/ocaml-wasm/wasm_of_ocaml/pull/48.

**Pull request merged**
